[package]
name = "eule-rs"
version = "0.1.0"
authors = ["Hercules <hercosmith03@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5"
bignum = {git = "https://github.com/ProfHercules/bignum", branch = "main"}